db.menu.insertMany([
 { id: 1, nombre: 'Pastel de carne', descripcion: 'Pastel relleno de carne, con su principal ingrediente que es la carne', precio: 30000, categoria: 'Plato principal', tiempoPreparacion: 40, calorias: 149, ingredientesPrincipales: 'Carne', nivelPicante: 'No tiene', disponibilidad: 40, popularidad: 5 },
    { id: 2, nombre: 'Hamburguesa clásica', descripcion: 'Formación clásica de hamburguesa, pan artesanal, carne hecha a mano y salsas de la casa', precio: 15000, categoria: 'Plato principal', tiempoPreparacion: 20, calorias: 300, ingredientesPrincipales: 'Carne artesanal, pan realizado por nosotros, vegetales frescos y salsa de la casa', nivelPicante: 'No tiene', disponibilidad: 40, popularidad: 7 },
    { id: 3, nombre: 'Hamburguesa ranchera', descripcion: 'Hamburguesa con ingredientes tradicionales del campo, como queso campesino y cebolla caramelizada.', precio: 18000, categoria: 'Plato principal', tiempoPreparacion: 25, calorias: 350, ingredientesPrincipales: 'Carne de res, queso campesino, cebolla caramelizada, pan artesanal, lechuga, tomate', nivelPicante: 'Bajo', disponibilidad: 35, popularidad: 6 },
    { id: 4, nombre: 'Perro caliente clásico', descripcion: 'Perro caliente tradicional con salchicha de calidad, mostaza, ketchup y mayonesa.', precio: 8000, categoria: 'Entrada', tiempoPreparacion: 10, calorias: 250, ingredientesPrincipales: 'Salchicha, pan, mostaza, ketchup, mayonesa', nivelPicante: 'No tiene', disponibilidad: 50, popularidad: 8 },
    { id: 5, nombre: 'Postre de tiramisú', descripcion: 'Delicioso tiramisú casero con capas de bizcocho, crema de mascarpone y cacao.', precio: 12000, categoria: 'Postre', tiempoPreparacion: 30, calorias: 400, ingredientesPrincipales: 'Bizcocho, mascarpone, café, cacao, azúcar, huevos', nivelPicante: 'No tiene', disponibilidad: 20, popularidad: 9 },
    { id: 6, nombre: 'Patacones con ahogado', descripcion: 'Patacones crujientes acompañados de un guiso ahogado de carne.', precio: 14000, categoria: 'Plato principal', tiempoPreparacion: 35, calorias: 500, ingredientesPrincipales: 'Plátano verde, carne de res, especias, cebolla, tomate', nivelPicante: 'Medio', disponibilidad: 25, popularidad: 7 },
    { id: 7, nombre: 'Tostones mixto', descripcion: 'Tostones servidos con una variedad de salsas y toppings.', precio: 10000, categoria: 'Entrada', tiempoPreparacion: 15, calorias: 300, ingredientesPrincipales: 'Plátano verde, salsas variadas, queso rallado, jalapeños', nivelPicante: 'Bajo', disponibilidad: 45, popularidad: 8 },
    { id: 8, nombre: 'Sándwich cubano', descripcion: 'Sándwich tradicional cubano con cerdo, jamón, queso suizo y encurtidos.', precio: 16000, categoria: 'Plato principal', tiempoPreparacion: 20, calorias: 400, ingredientesPrincipales: 'Cerdo, jamón, queso suizo, pepinillos, mostaza, pan cubano', nivelPicante: 'No tiene', disponibilidad: 30, popularidad: 7 },
    { id: 9, nombre: 'Sushi', descripcion: 'Variedad de sushi fresco con pescado de alta calidad y arroz sazonado.', precio: 25000, categoria: 'Plato principal', tiempoPreparacion: 25, calorias: 200, ingredientesPrincipales: 'Pescado fresco, arroz, alga nori, vinagre, soja', nivelPicante: 'No tiene', disponibilidad: 20, popularidad: 9 },
    { id: 10, nombre: 'Helado de chocolate', descripcion: 'Helado cremoso de chocolate con trozos de chocolate.', precio: 7000, categoria: 'Postre', tiempoPreparacion: 5, calorias: 300, ingredientesPrincipales: 'Leche, cacao, azúcar, crema', nivelPicante: 'No tiene', disponibilidad: 60, popularidad: 8 },
    { id: 11, nombre: '1/4 de pollo frito', descripcion: 'Cuarto de pollo frito crujiente con especias secretas.', precio: 20000, categoria: 'Plato principal', tiempoPreparacion: 30, calorias: 600, ingredientesPrincipales: 'Pollo, especias, aceite, harina', nivelPicante: 'Bajo', disponibilidad: 25, popularidad: 8 },
    { id: 12, nombre: 'Alitas de pollo', descripcion: 'Alitas de pollo marinadas y fritas, servidas con salsa picante.', precio: 12000, categoria: 'Entrada', tiempoPreparacion: 20, calorias: 350, ingredientesPrincipales: 'Pollo, salsa picante, ajo, especias', nivelPicante: 'Alto', disponibilidad: 40, popularidad: 7 },
    { id: 13, nombre: 'Nuggets de pollo', descripcion: 'Nuggets de pollo crujientes acompañados de salsas variadas.', precio: 9000, categoria: 'Entrada', tiempoPreparacion: 15, calorias: 400, ingredientesPrincipales: 'Pollo, pan rallado, salsas diversas', nivelPicante: 'No tiene', disponibilidad: 50, popularidad: 6 },
    { id: 14, nombre: 'Burritos', descripcion: 'Burritos rellenos de carne, frijoles, queso y vegetales.', precio: 14000, categoria: 'Plato principal', tiempoPreparacion: 25, calorias: 450, ingredientesPrincipales: 'Tortilla de harina, carne de res, frijoles, queso, lechuga, tomate', nivelPicante: 'Medio', disponibilidad: 35, popularidad: 7 },
    { id: 15, nombre: 'Tacos', descripcion: 'Tacos de carne asada con cilantro, cebolla y salsa.', precio: 10000, categoria: 'Plato principal', tiempoPreparacion: 20, calorias: 300, ingredientesPrincipales: 'Tortillas de maíz, carne asada, cilantro, cebolla, salsa picante', nivelPicante: 'Medio', disponibilidad: 50, popularidad: 9 },
    { id: 16, nombre: 'Bandeja paisa', descripcion: 'Plato típico de la region Andina con arroz, frijoles, carne, chicharrón, plátano y huevo.', precio: 25000, categoria: 'Plato principal', tiempoPreparacion: 50, calorias: 800, ingredientesPrincipales: 'Arroz, frijoles, carne molida, chicharrón, plátano, huevo, aguacate', nivelPicante: 'No tiene', disponibilidad: 15, popularidad: 10 },
    { id: 17, nombre: 'Cuy', descripcion: 'Cuy asado al estilo tradicional, servido con papas y ensalada.', precio: 30000, categoria: 'Plato principal', tiempoPreparacion: 60, calorias: 700, ingredientesPrincipales: 'Cuy, papas, ensalada fresca', nivelPicante: 'Bajo', disponibilidad: 10, popularidad: 6 },
    { id: 18, nombre: 'Frito', descripcion: 'Delicioso frito con papa y crispteas.', precio: 18000, categoria: 'Plato principal', tiempoPreparacion: 30, calorias: 650, ingredientesPrincipales: 'Carnes, papa, yuca, crispetas, especias', nivelPicante: 'Medio', disponibilidad: 20, popularidad: 7 },
    { id: 19, nombre: 'Pizza hawaiana', descripcion: 'Pizza con jamón y piña, combinación tropical.', precio: 22000, categoria: 'Plato principal', tiempoPreparacion: 25, calorias: 500, ingredientesPrincipales: 'Masa de pizza, jamón, piña, queso mozzarella, salsa de tomate', nivelPicante: 'No tiene', disponibilidad: 30, popularidad: 8 },
    { id: 20, nombre: 'Chuleta de cerdo', descripcion: 'Chuleta de cerdo jugosa a la parrilla con especias.', precio: 20000, categoria: 'Plato principal', tiempoPreparacion: 30, calorias: 550, ingredientesPrincipales: 'Chuleta de cerdo, especias, aceite de oliva', nivelPicante: 'Bajo', disponibilidad: 25, popularidad: 7 },
    { id: 21, nombre: 'Chuleta de pollo', descripcion: 'Chuleta de pollo empanizada y frita, servida con papas fritas.', precio: 18000, categoria: 'Plato principal', tiempoPreparacion: 25, calorias: 500, ingredientesPrincipales: 'Pechuga de pollo, pan rallado, huevo, papas', nivelPicante: 'No tiene', disponibilidad: 35, popularidad: 8 },
    { id: 22, nombre: 'Nachos con queso', descripcion: 'Nachos crujientes cubiertos con queso derretido y jalapeños.', precio: 12000, categoria: 'Entrada', tiempoPreparacion: 10, calorias: 400, ingredientesPrincipales: 'Totopos, queso cheddar, jalapeños, salsa', nivelPicante: 'Medio', disponibilidad: 40, popularidad: 8 },
    { id: 23, nombre: 'Sachipapa ranchera', descripcion: 'Sabrosa sachipapa con ingredientes al estilo ranchero.', precio: 16000, categoria: 'Plato principal', tiempoPreparacion: 20, calorias: 450, ingredientesPrincipales: 'Carne de res, papas, especias, cebolla, ajo', nivelPicante: 'Bajo', disponibilidad: 30, popularidad: 7 },
    { id: 24, nombre: 'Conejo', descripcion: 'Conejo guisado con hierbas y vegetales.', precio: 22000, categoria: 'Plato principal', tiempoPreparacion: 45, calorias: 600, ingredientesPrincipales: 'Conejo, hierbas frescas, zanahorias, apio, cebolla', nivelPicante: 'Bajo', disponibilidad: 15, popularidad: 5 },
    { id: 25, nombre: 'Fritanga', descripcion: 'Variedad de carnes fritas servidas con acompañamientos tradicionales.', precio: 25000, categoria: 'Plato principal', tiempoPreparacion: 35, calorias: 700, ingredientesPrincipales: 'Chicharrón, morcilla, pollo frito, yuca, plátano', nivelPicante: 'Medio', disponibilidad: 20, popularidad: 9 },
    { id: 26, nombre: 'Lechona', descripcion: 'Lechona rellena de arroz, guisantes y especias, asada a la perfección.', precio: 30000, categoria: 'Plato principal', tiempoPreparacion: 120, calorias: 800, ingredientesPrincipales: 'Cerdo, arroz, guisantes, especias, cebolla', nivelPicante: 'No tiene', disponibilidad: 10, popularidad: 8 },
    { id: 27, nombre: 'Ajiaco', descripcion: 'Sopa tradicional colombiana con pollo, papas y mazorca.', precio: 18000, categoria: 'Plato principal', tiempoPreparacion: 60, calorias: 400, ingredientesPrincipales: 'Pollo, papas, mazorca, guasca, crema de leche', nivelPicante: 'No tiene', disponibilidad: 15, popularidad: 9 },
    { id: 28, nombre: 'Picada', descripcion: 'Tabla de embutidos, quesos y snacks para compartir.', precio: 22000, categoria: 'Entrada', tiempoPreparacion: 15, calorias: 500, ingredientesPrincipales: 'Embutidos variados, quesos, aceitunas, pan, frutos secos', nivelPicante: 'Varía', disponibilidad: 25, popularidad: 7 },
    { id: 29, nombre: 'Alfajores', descripcion: 'Dulces tradicionales rellenos de dulce de leche y cubiertos con chocolate.', precio: 8000, categoria: 'Postre', tiempoPreparacion: 20, calorias: 300, ingredientesPrincipales: 'Harina, dulce de leche, chocolate, azúcar glas', nivelPicante: 'No tiene', disponibilidad: 40, popularidad: 8 },
    { id: 30, nombre: 'Trucha', descripcion: 'Trucha fresca a la parrilla con hierbas y limón.', precio: 22000, categoria: 'Plato principal', tiempoPreparacion: 25, calorias: 350, ingredientesPrincipales: 'Trucha, hierbas frescas, limón, aceite de oliva', nivelPicante: 'Bajo', disponibilidad: 20, popularidad: 6 },
    { id: 31, nombre: 'Cangrejo', descripcion: 'Cangrejo al ajillo con especias y acompañamiento de vegetales.', precio: 25000, categoria: 'Plato principal', tiempoPreparacion: 30, calorias: 450, ingredientesPrincipales: 'Cangrejo, ajo, perejil, aceite de oliva, especias', nivelPicante: 'Alto', disponibilidad: 15, popularidad: 7 },
    { id: 32, nombre: 'Camarones apanados', descripcion: 'Camarones frescos empanizados y fritos, servidos con salsa tártara.', precio: 20000, categoria: 'Plato principal', tiempoPreparacion: 20, calorias: 400, ingredientesPrincipales: 'Camarones, pan rallado, huevo, salsa tártara', nivelPicante: 'No tiene', disponibilidad: 30, popularidad: 8 },
    { id: 33, nombre: 'Arroz mixto', descripcion: 'Arroz cocido con una mezcla de vegetales, carnes y especias.', precio: 12000, categoria: 'Plato principal', tiempoPreparacion: 20, calorias: 300, ingredientesPrincipales: 'Arroz, vegetales mixtos, carne de res, pollo, especias', nivelPicante: 'Bajo', disponibilidad: 50, popularidad: 7 },
    { id: 34, nombre: 'Melcocha', descripcion: 'Dulce tradicional de melaza y azúcar, suave y pegajoso.', precio: 5000, categoria: 'Postre', tiempoPreparacion: 10, calorias: 250, ingredientesPrincipales: 'Azúcar, melaza, agua', nivelPicante: 'No tiene', disponibilidad: 60, popularidad: 6 },
    { id: 35, nombre: 'Merengón', descripcion: 'Postre de merengue con frutas frescas y crema chantilly.', precio: 10000, categoria: 'Postre', tiempoPreparacion: 15, calorias: 350, ingredientesPrincipales: 'Merengue, fresas, kiwi, crema chantilly', nivelPicante: 'No tiene', disponibilidad: 30, popularidad: 8 },
    { id: 36, nombre: 'Chocolate caliente', descripcion: 'Chocolate caliente espeso y cremoso, perfecto para cualquier momento.', precio: 7000, categoria: 'Bebida', tiempoPreparacion: 10, calorias: 300, ingredientesPrincipales: 'Cacao, leche, azúcar, canela', nivelPicante: 'No tiene', disponibilidad: 50, popularidad: 9 },
    { id: 37, nombre: 'Jugos naturales', descripcion: 'Variedad de jugos naturales frescos de frutas de temporada.', precio: 6000, categoria: 'Bebida', tiempoPreparacion: 5, calorias: 150, ingredientesPrincipales: 'Frutas frescas (naranja, mango, fresa, piña)', nivelPicante: 'No tiene', disponibilidad: 80, popularidad: 9 },
    { id: 38, nombre: 'Cerveza', descripcion: 'Selección de cervezas nacionales e importadas.', precio: 8000, categoria: 'Bebida', tiempoPreparacion: 0, calorias: 200, ingredientesPrincipales: 'Cebada, lúpulo, agua, levadura', nivelPicante: 'No tiene', disponibilidad: 100, popularidad: 10 },
    { id: 39, nombre: 'Coca-Cola', descripcion: 'Refresco clásico de Coca-Cola, bien frío y refrescante.', precio: 4000, categoria: 'Bebida', tiempoPreparacion: 0, calorias: 150, ingredientesPrincipales: 'Agua carbonatada, azúcar, cafeína, saborizantes', nivelPicante: 'No tiene', disponibilidad: 100, popularidad: 10 },
    { id: 40, nombre: 'Quimbolito', descripcion: 'Pastel con uvas pasas y en algunos casos trozos de chocolate, envueltos y cocidos en hojas.', precio: 15000, categoria: 'Plato principal', tiempoPreparacion: 30, calorias: 350, ingredientesPrincipales: 'harina de maíz, mantequilla, huevo, queso, uvas pasas', nivelPicante: 'Medio', disponibilidad: 20, popularidad: 6 }
   
]);

//db.menu.find({nombre:{$eq:'Pastel de carne'}})
//db.menu.find({categoria:{$gt:'Bebida'}}) 
//db.menu.find({tiempoPreparacion:{$gte:50}})
//db.menu.find({disponibilidad:{$lt:20}})
//db.menu.find({popularidad:{$lte:6}})
//db.menu.find({nivelPicante:{$ne:'bajo'}})
//db.menu.find({calorias: {$in: [200, 600]}})
//db.menu.find({categoria: {$nin: ['Plato principal', 'Entrada']}})
//db.menu.find({precio:{$gte: 20000}})
// actualizar
//db.menu.updateOne({ id: 30 },{ $set: { disponibilidad: 0 } });
//db.menu.find({id: {$eq: 30}})