const cardCodeDetails = {
    "1": {
      code: `        
    {
    _id: ObjectId('66f4912b8d9a0d657742f82a'),
    id: 36,
    nombre: 'Mecanica',
    codigo: '122121',
    Descripcion: 'Se enseñan los funcionamientos las leyes que rigen en nuestro planeta',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Favio',
    aula: 'Laboratorio',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  }
  `
    },
    "2": {
      code: `
      {
    _id: ObjectId('66f491756c51c76f6042f808'),
    id: 2,
    nombre: 'Estructuras de datos 2 ',
    codigo: '212391',
    Descripcion: 'Se enseña el uso de arboles binarios y grafos para la programacion',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Fabian',
    aula: 'MI 604',
    prerrequisitos: 'Estructuras de datos',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f491756c51c76f6042f809'),
    id: 3,
    nombre: 'Estructuras de datos',
    codigo: '212391',
    Descripcion: 'Se plante como es la organizacion de organizacion de datos en el backend',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Fabian',
    aula: 'MI 603',
    prerrequisitos: 'Apo 3',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f491756c51c76f6042f813'),
    id: 13,
    nombre: 'Ingles A1',
    codigo: '112911',
    Descripcion: 'Se enseña a formar oraciones en tiempo presente',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Camilo',
    aula: 'JN 404',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f491756c51c76f6042f814'),
    id: 14,
    nombre: 'Ingles A2',
    codigo: '112867',
    Descripcion: 'Se enseña comparativos y superlativos',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Lucia',
    aula: 'SJ 204',
    prerrequisitos: 'Ingles a1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491756c51c76f6042f815'),
    id: 15,
    nombre: 'Ingles B1',
    codigo: '112917',
    Descripcion: 'Se enseñan conjugar en diferentes tiempos y prhasal verbs',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Diana',
    aula: 'SC 204',
    prerrequisitos: 'Inbles a2',
    promedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f491756c51c76f6042f816'),
    id: 16,
    nombre: 'Inbles B2',
    codigo: '112912',
    Descripcion: 'Se enseña a mantener conversaciones con extranjeros',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Camilo',
    aula: 'SC 206',
    prerrequisitos: 'Ingles b1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491756c51c76f6042f81b'),
    id: 21,
    nombre: 'Electronica digital',
    codigo: '222987',
    Descripcion: 'Se practica y enseña las diferencias entre dispositivos digitales y analogicos',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Javier',
    aula: 'Laboratorio',
    prerrequisitos: 'Electricidad y magnetismo',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491756c51c76f6042f82a'),
    id: 36,
    nombre: 'Mecanica',
    codigo: '122121',
    Descripcion: 'Se enseñan los funcionamientos las leyes que rigen en nuestro planeta',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Favio',
    aula: 'Laboratorio',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491756c51c76f6042f82e'),
    id: 40,
    nombre: 'Practica de base de datos',
    codigo: '212544',
    Descripcion: 'Se pone en practica lo aprendido en teoria de base de datos',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 160,
    profesorResponsable: 'Carrera',
    aula: 'MI 601',
    prerrequisitos: 'Teoria de base de datos',
    promedioCalificaciones: 4
  }      
  `
    },
    "3": {
      code: `
       {
    _id: ObjectId('66f49196e1df4f6a9c42f807'),
    id: 1,
    nombre: 'Procesos de investigación',
    codigo: '222113',
    Descripcion: 'En esta matera se plantean ideas para el desarrollo de su tesis',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 149,
    profesorResponsable: 'Andres',
    aula: 'SJ 304',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f808'),
    id: 2,
    nombre: 'Estructuras de datos 2 ',
    codigo: '212391',
    Descripcion: 'Se enseña el uso de arboles binarios y grafos para la programacion',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Fabian',
    aula: 'MI 604',
    prerrequisitos: 'Estructuras de datos',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f809'),
    id: 3,
    nombre: 'Estructuras de datos',
    codigo: '212391',
    Descripcion: 'Se plante como es la organizacion de organizacion de datos en el backend',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Fabian',
    aula: 'MI 603',
    prerrequisitos: 'Apo 3',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f80a'),
    id: 4,
    nombre: 'Procesos de investigación 2',
    codigo: '221872',
    Descripcion: 'En esta matera se plante el desarrollo de los objetivos especificos del trabajo de grado',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 604',
    prerrequisitos: 'Procesos de investigacion',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f80b'),
    id: 5,
    nombre: 'Calculo diferencial',
    codigo: '211918',
    Descripcion: 'Se enseña que es el diferencial y porque estan importante',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 304',
    prerrequisitos: 'Fundamentos matematicos',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f80c'),
    id: 6,
    nombre: 'Calculo integral',
    codigo: '212223',
    Descripcion: 'Se enseña como calcular integrales y su uso en casos reales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'SJ 204',
    prerrequisitos: 'Calculo diferencial',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f80d'),
    id: 7,
    nombre: 'Algebra',
    codigo: '222123',
    Descripcion: 'Se fortalecen el algebra y se amplia con el uso de matrices',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 306',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f80e'),
    id: 8,
    nombre: 'Python basico',
    codigo: '222413',
    Descripcion: 'Se enseñan las bases de python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f80f'),
    id: 9,
    nombre: 'Seguridad informatica',
    codigo: '298173',
    Descripcion: 'Se enseñan los diferentes tipos de ataques y como defenderse ante ellos',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Madeline',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f810'),
    id: 10,
    nombre: 'Humanismo cristiano',
    codigo: '212352',
    Descripcion: 'Se comparten las enseñanzas marianas y como llevarlas al ambito profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Jorge',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f811'),
    id: 11,
    nombre: 'Etica profesional',
    codigo: '221234',
    Descripcion: 'Se busca enseñar sobre la moral en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 103',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f812'),
    id: 12,
    nombre: 'Lecto escritura',
    codigo: '211191',
    Descripcion: 'Se enseñan las habilidades de lectura y escritura orientada a ingenieria ¿',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f813'),
    id: 13,
    nombre: 'Ingles A1',
    codigo: '112911',
    Descripcion: 'Se enseña a formar oraciones en tiempo presente',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Camilo',
    aula: 'JN 404',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f814'),
    id: 14,
    nombre: 'Ingles A2',
    codigo: '112867',
    Descripcion: 'Se enseña comparativos y superlativos',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Lucia',
    aula: 'SJ 204',
    prerrequisitos: 'Ingles a1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f815'),
    id: 15,
    nombre: 'Ingles B1',
    codigo: '112917',
    Descripcion: 'Se enseñan conjugar en diferentes tiempos y prhasal verbs',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Diana',
    aula: 'SC 204',
    prerrequisitos: 'Inbles a2',
    promedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f816'),
    id: 16,
    nombre: 'Inbles B2',
    codigo: '112912',
    Descripcion: 'Se enseña a mantener conversaciones con extranjeros',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Camilo',
    aula: 'SC 206',
    prerrequisitos: 'Ingles b1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f817'),
    id: 17,
    nombre: 'Introduccion a la ingenieria',
    codigo: '212363',
    Descripcion: 'Se introduce las tematicas a abordad en la carrera y los campos profesionales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Magda',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f818'),
    id: 18,
    nombre: 'Pensamiento filosofico',
    codigo: '222717',
    Descripcion: 'Se enseña el pensamiento critico y como este influye en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f819'),
    id: 19,
    nombre: 'Fundamentos matematicos',
    codigo: '222177',
    Descripcion: 'Se fortalezen las bases de las matematicas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'MI 602',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f49196e1df4f6a9c42f81a'),
    id: 20,
    nombre: 'Redes',
    codigo: '222788',
    Descripcion: 'Se enseñan los fundamentos de las redes y como emplearlas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 601',
    prerrequisitos: 'Simulacion',
    promedioCalificaciones: 4.4
  }
             `
    },
    "4": {
      code: `
      {
    _id: ObjectId('66f491c5ea6bdd171942f807'),
    id: 1,
    nombre: 'Procesos de investigación',
    codigo: '222113',
    Descripcion: 'En esta matera se plantean ideas para el desarrollo de su tesis',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 149,
    profesorResponsable: 'Andres',
    aula: 'SJ 304',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f80a'),
    id: 4,
    nombre: 'Procesos de investigación 2',
    codigo: '221872',
    Descripcion: 'En esta matera se plante el desarrollo de los objetivos especificos del trabajo de grado',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 604',
    prerrequisitos: 'Procesos de investigacion',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f80b'),
    id: 5,
    nombre: 'Calculo diferencial',
    codigo: '211918',
    Descripcion: 'Se enseña que es el diferencial y porque estan importante',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 304',
    prerrequisitos: 'Fundamentos matematicos',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f80c'),
    id: 6,
    nombre: 'Calculo integral',
    codigo: '212223',
    Descripcion: 'Se enseña como calcular integrales y su uso en casos reales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'SJ 204',
    prerrequisitos: 'Calculo diferencial',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f80d'),
    id: 7,
    nombre: 'Algebra',
    codigo: '222123',
    Descripcion: 'Se fortalecen el algebra y se amplia con el uso de matrices',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 306',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f80e'),
    id: 8,
    nombre: 'Python basico',
    codigo: '222413',
    Descripcion: 'Se enseñan las bases de python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f80f'),
    id: 9,
    nombre: 'Seguridad informatica',
    codigo: '298173',
    Descripcion: 'Se enseñan los diferentes tipos de ataques y como defenderse ante ellos',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Madeline',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f810'),
    id: 10,
    nombre: 'Humanismo cristiano',
    codigo: '212352',
    Descripcion: 'Se comparten las enseñanzas marianas y como llevarlas al ambito profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Jorge',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f811'),
    id: 11,
    nombre: 'Etica profesional',
    codigo: '221234',
    Descripcion: 'Se busca enseñar sobre la moral en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 103',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f812'),
    id: 12,
    nombre: 'Lecto escritura',
    codigo: '211191',
    Descripcion: 'Se enseñan las habilidades de lectura y escritura orientada a ingenieria ¿',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f817'),
    id: 17,
    nombre: 'Introduccion a la ingenieria',
    codigo: '212363',
    Descripcion: 'Se introduce las tematicas a abordad en la carrera y los campos profesionales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Magda',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f818'),
    id: 18,
    nombre: 'Pensamiento filosofico',
    codigo: '222717',
    Descripcion: 'Se enseña el pensamiento critico y como este influye en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f819'),
    id: 19,
    nombre: 'Fundamentos matematicos',
    codigo: '222177',
    Descripcion: 'Se fortalezen las bases de las matematicas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'MI 602',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f81a'),
    id: 20,
    nombre: 'Redes',
    codigo: '222788',
    Descripcion: 'Se enseñan los fundamentos de las redes y como emplearlas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 601',
    prerrequisitos: 'Simulacion',
    promedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f81c'),
    id: 22,
    nombre: 'Teoria de base de datos',
    codigo: '222182',
    Descripcion: 'Se enseñan los diferentes tipos de bases de datos que existen y sus diferencias',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 603',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f81d'),
    id: 23,
    nombre: 'Python intermedio',
    codigo: '222875',
    Descripcion: 'Se enseña la programacion orientada a objetos en python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 601',
    prerrequisitos: 'Python basico',
    promedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f81e'),
    id: 24,
    nombre: 'Python avanzado',
    codigo: '221981',
    Descripcion: 'Se enseña la parte empresarial de python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 603',
    prerrequisitos: 'Python intermedio',
    promedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f81f'),
    id: 25,
    nombre: 'Cloud computing',
    codigo: '211421',
    Descripcion: 'Se enseña que tan importante ha sido el cloud computing y como aprovecharlo ',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'gustavo',
    aula: 'MI 602',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f820'),
    id: 26,
    nombre: 'Desarrollo movil',
    codigo: '222911',
    Descripcion: 'Se enseña a llevar programas pequeños a dispositivos moviles',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Gustavo',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f491c5ea6bdd171942f821'),
    id: 27,
    nombre: 'Estadistica inferencial',
    codigo: '222763',
    Descripcion: 'Se enseñan las bases de la estadistica y como emplearla en el ambito empresarial ',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'MI 602',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  }
            `
    },
    "5": {
      code: `
        {
    _id: ObjectId('66f491e274740dff8742f807'),
    id: 1,
    nombre: 'Procesos de investigación',
    codigo: '222113',
    Descripcion: 'En esta matera se plantean ideas para el desarrollo de su tesis',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 149,
    profesorResponsable: 'Andres',
    aula: 'SJ 304',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491e274740dff8742f808'),
    id: 2,
    nombre: 'Estructuras de datos 2 ',
    codigo: '212391',
    Descripcion: 'Se enseña el uso de arboles binarios y grafos para la programacion',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Fabian',
    aula: 'MI 604',
    prerrequisitos: 'Estructuras de datos',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f491e274740dff8742f809'),
    id: 3,
    nombre: 'Estructuras de datos',
    codigo: '212391',
    Descripcion: 'Se plante como es la organizacion de organizacion de datos en el backend',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Fabian',
    aula: 'MI 603',
    prerrequisitos: 'Apo 3',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f491e274740dff8742f80a'),
    id: 4,
    nombre: 'Procesos de investigación 2',
    codigo: '221872',
    Descripcion: 'En esta matera se plante el desarrollo de los objetivos especificos del trabajo de grado',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 604',
    prerrequisitos: 'Procesos de investigacion',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491e274740dff8742f80b'),
    id: 5,
    nombre: 'Calculo diferencial',
    codigo: '211918',
    Descripcion: 'Se enseña que es el diferencial y porque estan importante',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 304',
    prerrequisitos: 'Fundamentos matematicos',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491e274740dff8742f80c'),
    id: 6,
    nombre: 'Calculo integral',
    codigo: '212223',
    Descripcion: 'Se enseña como calcular integrales y su uso en casos reales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'SJ 204',
    prerrequisitos: 'Calculo diferencial',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491e274740dff8742f80d'),
    id: 7,
    nombre: 'Algebra',
    codigo: '222123',
    Descripcion: 'Se fortalecen el algebra y se amplia con el uso de matrices',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 306',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491e274740dff8742f80e'),
    id: 8,
    nombre: 'Python basico',
    codigo: '222413',
    Descripcion: 'Se enseñan las bases de python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f491e274740dff8742f810'),
    id: 10,
    nombre: 'Humanismo cristiano',
    codigo: '212352',
    Descripcion: 'Se comparten las enseñanzas marianas y como llevarlas al ambito profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Jorge',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491e274740dff8742f811'),
    id: 11,
    nombre: 'Etica profesional',
    codigo: '221234',
    Descripcion: 'Se busca enseñar sobre la moral en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 103',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f491e274740dff8742f812'),
    id: 12,
    nombre: 'Lecto escritura',
    codigo: '211191',
    Descripcion: 'Se enseñan las habilidades de lectura y escritura orientada a ingenieria ¿',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f491e274740dff8742f813'),
    id: 13,
    nombre: 'Ingles A1',
    codigo: '112911',
    Descripcion: 'Se enseña a formar oraciones en tiempo presente',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Camilo',
    aula: 'JN 404',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f491e274740dff8742f814'),
    id: 14,
    nombre: 'Ingles A2',
    codigo: '112867',
    Descripcion: 'Se enseña comparativos y superlativos',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Lucia',
    aula: 'SJ 204',
    prerrequisitos: 'Ingles a1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491e274740dff8742f815'),
    id: 15,
    nombre: 'Ingles B1',
    codigo: '112917',
    Descripcion: 'Se enseñan conjugar en diferentes tiempos y prhasal verbs',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Diana',
    aula: 'SC 204',
    prerrequisitos: 'Inbles a2',
    promedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f491e274740dff8742f816'),
    id: 16,
    nombre: 'Inbles B2',
    codigo: '112912',
    Descripcion: 'Se enseña a mantener conversaciones con extranjeros',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Camilo',
    aula: 'SC 206',
    prerrequisitos: 'Ingles b1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f491e274740dff8742f817'),
    id: 17,
    nombre: 'Introduccion a la ingenieria',
    codigo: '212363',
    Descripcion: 'Se introduce las tematicas a abordad en la carrera y los campos profesionales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Magda',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f491e274740dff8742f818'),
    id: 18,
    nombre: 'Pensamiento filosofico',
    codigo: '222717',
    Descripcion: 'Se enseña el pensamiento critico y como este influye en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f491e274740dff8742f819'),
    id: 19,
    nombre: 'Fundamentos matematicos',
    codigo: '222177',
    Descripcion: 'Se fortalezen las bases de las matematicas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'MI 602',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f491e274740dff8742f81a'),
    id: 20,
    nombre: 'Redes',
    codigo: '222788',
    Descripcion: 'Se enseñan los fundamentos de las redes y como emplearlas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 601',
    prerrequisitos: 'Simulacion',
    promedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f491e274740dff8742f81b'),
    id: 21,
    nombre: 'Electronica digital',
    codigo: '222987',
    Descripcion: 'Se practica y enseña las diferencias entre dispositivos digitales y analogicos',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Javier',
    aula: 'Laboratorio',
    prerrequisitos: 'Electricidad y magnetismo',
    promedioCalificaciones: 4
  }    
    `
    },
    "6": {
      code: `
           {
    _id: ObjectId('66f492056fcc8175cc42f807'),
    id: 1,
    nombre: 'Procesos de investigación',
    codigo: '222113',
    Descripcion: 'En esta matera se plantean ideas para el desarrollo de su tesis',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 149,
    profesorResponsable: 'Andres',
    aula: 'SJ 304',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f808'),
    id: 2,
    nombre: 'Estructuras de datos 2 ',
    codigo: '212391',
    Descripcion: 'Se enseña el uso de arboles binarios y grafos para la programacion',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Fabian',
    aula: 'MI 604',
    prerrequisitos: 'Estructuras de datos',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f809'),
    id: 3,
    nombre: 'Estructuras de datos',
    codigo: '212391',
    Descripcion: 'Se plante como es la organizacion de organizacion de datos en el backend',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Fabian',
    aula: 'MI 603',
    prerrequisitos: 'Apo 3',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f80a'),
    id: 4,
    nombre: 'Procesos de investigación 2',
    codigo: '221872',
    Descripcion: 'En esta matera se plante el desarrollo de los objetivos especificos del trabajo de grado',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 604',
    prerrequisitos: 'Procesos de investigacion',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f80b'),
    id: 5,
    nombre: 'Calculo diferencial',
    codigo: '211918',
    Descripcion: 'Se enseña que es el diferencial y porque estan importante',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 304',
    prerrequisitos: 'Fundamentos matematicos',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f80c'),
    id: 6,
    nombre: 'Calculo integral',
    codigo: '212223',
    Descripcion: 'Se enseña como calcular integrales y su uso en casos reales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'SJ 204',
    prerrequisitos: 'Calculo diferencial',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f80d'),
    id: 7,
    nombre: 'Algebra',
    codigo: '222123',
    Descripcion: 'Se fortalecen el algebra y se amplia con el uso de matrices',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 306',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f80f'),
    id: 9,
    nombre: 'Seguridad informatica',
    codigo: '298173',
    Descripcion: 'Se enseñan los diferentes tipos de ataques y como defenderse ante ellos',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Madeline',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f810'),
    id: 10,
    nombre: 'Humanismo cristiano',
    codigo: '212352',
    Descripcion: 'Se comparten las enseñanzas marianas y como llevarlas al ambito profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Jorge',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f811'),
    id: 11,
    nombre: 'Etica profesional',
    codigo: '221234',
    Descripcion: 'Se busca enseñar sobre la moral en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 103',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f812'),
    id: 12,
    nombre: 'Lecto escritura',
    codigo: '211191',
    Descripcion: 'Se enseñan las habilidades de lectura y escritura orientada a ingenieria ¿',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f813'),
    id: 13,
    nombre: 'Ingles A1',
    codigo: '112911',
    Descripcion: 'Se enseña a formar oraciones en tiempo presente',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Camilo',
    aula: 'JN 404',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f814'),
    id: 14,
    nombre: 'Ingles A2',
    codigo: '112867',
    Descripcion: 'Se enseña comparativos y superlativos',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Lucia',
    aula: 'SJ 204',
    prerrequisitos: 'Ingles a1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f815'),
    id: 15,
    nombre: 'Ingles B1',
    codigo: '112917',
    Descripcion: 'Se enseñan conjugar en diferentes tiempos y prhasal verbs',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Diana',
    aula: 'SC 204',
    prerrequisitos: 'Inbles a2',
    promedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f816'),
    id: 16,
    nombre: 'Inbles B2',
    codigo: '112912',
    Descripcion: 'Se enseña a mantener conversaciones con extranjeros',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Camilo',
    aula: 'SC 206',
    prerrequisitos: 'Ingles b1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f817'),
    id: 17,
    nombre: 'Introduccion a la ingenieria',
    codigo: '212363',
    Descripcion: 'Se introduce las tematicas a abordad en la carrera y los campos profesionales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Magda',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f818'),
    id: 18,
    nombre: 'Pensamiento filosofico',
    codigo: '222717',
    Descripcion: 'Se enseña el pensamiento critico y como este influye en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f819'),
    id: 19,
    nombre: 'Fundamentos matematicos',
    codigo: '222177',
    Descripcion: 'Se fortalezen las bases de las matematicas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'MI 602',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f81a'),
    id: 20,
    nombre: 'Redes',
    codigo: '222788',
    Descripcion: 'Se enseñan los fundamentos de las redes y como emplearlas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 601',
    prerrequisitos: 'Simulacion',
    promedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f492056fcc8175cc42f81b'),
    id: 21,
    nombre: 'Electronica digital',
    codigo: '222987',
    Descripcion: 'Se practica y enseña las diferencias entre dispositivos digitales y analogicos',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Javier',
    aula: 'Laboratorio',
    prerrequisitos: 'Electricidad y magnetismo',
    promedioCalificaciones: 4
  } 
    `
    },
    "7": {
      code: `
            {
    _id: ObjectId('66f49249d13f80361642f808'),
    id: 2,
    nombre: 'Estructuras de datos 2 ',
    codigo: '212391',
    Descripcion: 'Se enseña el uso de arboles binarios y grafos para la programacion',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Fabian',
    aula: 'MI 604',
    prerrequisitos: 'Estructuras de datos',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f49249d13f80361642f80a'),
    id: 4,
    nombre: 'Procesos de investigación 2',
    codigo: '221872',
    Descripcion: 'En esta matera se plante el desarrollo de los objetivos especificos del trabajo de grado',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 604',
    prerrequisitos: 'Procesos de investigacion',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f49249d13f80361642f80e'),
    id: 8,
    nombre: 'Python basico',
    codigo: '222413',
    Descripcion: 'Se enseñan las bases de python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f49249d13f80361642f80f'),
    id: 9,
    nombre: 'Seguridad informatica',
    codigo: '298173',
    Descripcion: 'Se enseñan los diferentes tipos de ataques y como defenderse ante ellos',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Madeline',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f49249d13f80361642f812'),
    id: 12,
    nombre: 'Lecto escritura',
    codigo: '211191',
    Descripcion: 'Se enseñan las habilidades de lectura y escritura orientada a ingenieria ¿',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.5
  },
  {
    _id: ObjectId('66f49249d13f80361642f817'),
    id: 17,
    nombre: 'Introduccion a la ingenieria',
    codigo: '212363',
    Descripcion: 'Se introduce las tematicas a abordad en la carrera y los campos profesionales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Magda',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f49249d13f80361642f81a'),
    id: 20,
    nombre: 'Redes',
    codigo: '222788',
    Descripcion: 'Se enseñan los fundamentos de las redes y como emplearlas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 601',
    prerrequisitos: 'Simulacion',
    promedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f49249d13f80361642f81d'),
    id: 23,
    nombre: 'Python intermedio',
    codigo: '222875',
    Descripcion: 'Se enseña la programacion orientada a objetos en python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 601',
    prerrequisitos: 'Python basico',
    promedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f49249d13f80361642f820'),
    id: 26,
    nombre: 'Desarrollo movil',
    codigo: '222911',
    Descripcion: 'Se enseña a llevar programas pequeños a dispositivos moviles',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Gustavo',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f49249d13f80361642f822'),
    id: 28,
    nombre: 'Ecuaciones diferenciales',
    codigo: '212345',
    Descripcion: 'Se enseña como los problema cotidianos pueden ser expresados en ecuaciones diferenciales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'MI 601',
    prerrequisitos: 'Calculo integral',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f49249d13f80361642f823'),
    id: 29,
    nombre: 'Simulacion',
    codigo: '221810',
    Descripcion: 'Se enseñan las maneras en las que se puede simular al aleatoridad en programacion',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f49249d13f80361642f826'),
    id: 32,
    nombre: 'Analisis y modelamiento de software',
    codigo: '212211',
    Descripcion: 'Se enseña a conceptualizar los requerimientos ',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Giovanni',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.9
  },
  {
    _id: ObjectId('66f49249d13f80361642f827'),
    id: 33,
    nombre: 'Arquitectura de computadores',
    codigo: '242461',
    Descripcion: 'Se enseña la composicion y logica detras de los computadores',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Javier',
    aula: 'MI 604',
    prerrequisitos: 'Electronica digital',
    promedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f49249d13f80361642f82d'),
    id: 39,
    nombre: 'Interaccion hombre-maquina',
    codigo: '212673',
    Descripcion: 'Se enseña como hacer interfaces intuitivas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f49249d13f80361642f82e'),
    id: 40,
    nombre: 'Practica de base de datos',
    codigo: '212544',
    Descripcion: 'Se pone en practica lo aprendido en teoria de base de datos',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 160,
    profesorResponsable: 'Carrera',
    aula: 'MI 601',
    prerrequisitos: 'Teoria de base de datos',
    promedioCalificaciones: 4
  } 
    `
    },
    "8": {
      code: `
    {
    _id: ObjectId('66f4927fbddbc0385042f807'),
    id: 1,
    nombre: 'Procesos de investigación',
    codigo: '222113',
    Descripcion: 'En esta matera se plantean ideas para el desarrollo de su tesis',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 149,
    profesorResponsable: 'Andres',
    aula: 'SJ 304',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f80a'),
    id: 4,
    nombre: 'Procesos de investigación 2',
    codigo: '221872',
    Descripcion: 'En esta matera se plante el desarrollo de los objetivos especificos del trabajo de grado',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Alejandra',
    aula: 'MI 604',
    prerrequisitos: 'Procesos de investigacion',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f80c'),
    id: 6,
    nombre: 'Calculo integral',
    codigo: '212223',
    Descripcion: 'Se enseña como calcular integrales y su uso en casos reales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'SJ 204',
    prerrequisitos: 'Calculo diferencial',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f80e'),
    id: 8,
    nombre: 'Python basico',
    codigo: '222413',
    Descripcion: 'Se enseñan las bases de python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f810'),
    id: 10,
    nombre: 'Humanismo cristiano',
    codigo: '212352',
    Descripcion: 'Se comparten las enseñanzas marianas y como llevarlas al ambito profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Jorge',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f811'),
    id: 11,
    nombre: 'Etica profesional',
    codigo: '221234',
    Descripcion: 'Se busca enseñar sobre la moral en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 103',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f815'),
    id: 15,
    nombre: 'Ingles B1',
    codigo: '112917',
    Descripcion: 'Se enseñan conjugar en diferentes tiempos y prhasal verbs',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Diana',
    aula: 'SC 204',
    prerrequisitos: 'Inbles a2',
    promedioCalificaciones: 4.3
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f817'),
    id: 17,
    nombre: 'Introduccion a la ingenieria',
    codigo: '212363',
    Descripcion: 'Se introduce las tematicas a abordad en la carrera y los campos profesionales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Magda',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 5
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f818'),
    id: 18,
    nombre: 'Pensamiento filosofico',
    codigo: '222717',
    Descripcion: 'Se enseña el pensamiento critico y como este influye en lo profesional',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Einer',
    aula: 'MI 102',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f819'),
    id: 19,
    nombre: 'Fundamentos matematicos',
    codigo: '222177',
    Descripcion: 'Se fortalezen las bases de las matematicas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'MI 602',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f81a'),
    id: 20,
    nombre: 'Redes',
    codigo: '222788',
    Descripcion: 'Se enseñan los fundamentos de las redes y como emplearlas',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 601',
    prerrequisitos: 'Simulacion',
    promedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f81c'),
    id: 22,
    nombre: 'Teoria de base de datos',
    codigo: '222182',
    Descripcion: 'Se enseñan los diferentes tipos de bases de datos que existen y sus diferencias',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 603',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.8
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f81d'),
    id: 23,
    nombre: 'Python intermedio',
    codigo: '222875',
    Descripcion: 'Se enseña la programacion orientada a objetos en python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 601',
    prerrequisitos: 'Python basico',
    promedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f81e'),
    id: 24,
    nombre: 'Python avanzado',
    codigo: '221981',
    Descripcion: 'Se enseña la parte empresarial de python',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Mauricio',
    aula: 'MI 603',
    prerrequisitos: 'Python intermedio',
    promedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f820'),
    id: 26,
    nombre: 'Desarrollo movil',
    codigo: '222911',
    Descripcion: 'Se enseña a llevar programas pequeños a dispositivos moviles',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Gustavo',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.7
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f823'),
    id: 29,
    nombre: 'Simulacion',
    codigo: '221810',
    Descripcion: 'Se enseñan las maneras en las que se puede simular al aleatoridad en programacion',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Daniel',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.4
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f824'),
    id: 30,
    nombre: 'Constitucion y democracia',
    codigo: '2121741',
    Descripcion: 'Se enseñan los derechos y deberes que se deben cumplir como ciudadanso y profesionales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Javier',
    aula: 'MI  604',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.2
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f826'),
    id: 32,
    nombre: 'Analisis y modelamiento de software',
    codigo: '212211',
    Descripcion: 'Se enseña a conceptualizar los requerimientos ',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Giovanni',
    aula: 'MI 601',
    prerrequisitos: 'No',
    promedioCalificaciones: 4.9
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f827'),
    id: 33,
    nombre: 'Arquitectura de computadores',
    codigo: '242461',
    Descripcion: 'Se enseña la composicion y logica detras de los computadores',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Javier',
    aula: 'MI 604',
    prerrequisitos: 'Electronica digital',
    promedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f4927fbddbc0385042f828'),
    id: 34,
    nombre: 'Electricidad y magnetismo',
    codigo: '221443',
    Descripcion: 'Se enseñan como interactua la fisica y sus fenomes con nuestro entorno',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Favio',
    aula: 'SC 206',
    prerrequisitos: 'Mecanica',
    promedioCalificaciones: 5
  }
    `
    },
    "9": {
      code: `
        {
    _id: ObjectId('66f4929f721909371642f80b'),
    id: 5,
    nombre: 'Calculo diferencial',
    codigo: '211918',
    Descripcion: 'Se enseña que es el diferencial y porque estan importante',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 304',
    prerrequisitos: 'Fundamentos matematicos',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f4929f721909371642f80d'),
    id: 7,
    nombre: 'Algebra',
    codigo: '222123',
    Descripcion: 'Se fortalecen el algebra y se amplia con el uso de matrices',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Nancy',
    aula: 'JN 306',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f4929f721909371642f80f'),
    id: 9,
    nombre: 'Seguridad informatica',
    codigo: '298173',
    Descripcion: 'Se enseñan los diferentes tipos de ataques y como defenderse ante ellos',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Madeline',
    aula: 'MI 604',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f4929f721909371642f814'),
    id: 14,
    nombre: 'Ingles A2',
    codigo: '112867',
    Descripcion: 'Se enseña comparativos y superlativos',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Lucia',
    aula: 'SJ 204',
    prerrequisitos: 'Ingles a1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f4929f721909371642f816'),
    id: 16,
    nombre: 'Inbles B2',
    codigo: '112912',
    Descripcion: 'Se enseña a mantener conversaciones con extranjeros',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Camilo',
    aula: 'SC 206',
    prerrequisitos: 'Ingles b1',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f4929f721909371642f81b'),
    id: 21,
    nombre: 'Electronica digital',
    codigo: '222987',
    Descripcion: 'Se practica y enseña las diferencias entre dispositivos digitales y analogicos',
    creditos: 3,
    horasTeorica: 40,
    horasPractica: 180,
    profesorResponsable: 'Javier',
    aula: 'Laboratorio',
    prerrequisitos: 'Electricidad y magnetismo',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f4929f721909371642f81f'),
    id: 25,
    nombre: 'Cloud computing',
    codigo: '211421',
    Descripcion: 'Se enseña que tan importante ha sido el cloud computing y como aprovecharlo ',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'gustavo',
    aula: 'MI 602',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f4929f721909371642f822'),
    id: 28,
    nombre: 'Ecuaciones diferenciales',
    codigo: '212345',
    Descripcion: 'Se enseña como los problema cotidianos pueden ser expresados en ecuaciones diferenciales',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Leidy',
    aula: 'MI 601',
    prerrequisitos: 'Calculo integral',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f4929f721909371642f827'),
    id: 33,
    nombre: 'Arquitectura de computadores',
    codigo: '242461',
    Descripcion: 'Se enseña la composicion y logica detras de los computadores',
    creditos: 2,
    horasTeorica: 40,
    horasPractica: 140,
    profesorResponsable: 'Javier',
    aula: 'MI 604',
    prerrequisitos: 'Electronica digital',
    promedioCalificaciones: 3.5
  },
  {
    _id: ObjectId('66f4929f721909371642f82a'),
    id: 36,
    nombre: 'Mecanica',
    codigo: '122121',
    Descripcion: 'Se enseñan los funcionamientos las leyes que rigen en nuestro planeta',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 180,
    profesorResponsable: 'Favio',
    aula: 'Laboratorio',
    prerrequisitos: 'No',
    promedioCalificaciones: 4
  },
  {
    _id: ObjectId('66f4929f721909371642f82e'),
    id: 40,
    nombre: 'Practica de base de datos',
    codigo: '212544',
    Descripcion: 'Se pone en practica lo aprendido en teoria de base de datos',
    creditos: 3,
    horasTeorica: 50,
    horasPractica: 160,
    profesorResponsable: 'Carrera',
    aula: 'MI 601',
    prerrequisitos: 'Teoria de base de datos',
    promedioCalificaciones: 4
  }

      `
    },
    "10": {
      code: `
        mycompiler_mongodb> 
    mycompiler_mongodb> 
    mycompiler_mongodb> { acknowledged: true, deletedCount: 0 }
    mycompiler_mongodb> 
      `
    }
  };
  
  
  // Modal
  const modal = document.getElementById("modal");
  const modalCode = document.getElementById("modal-code");
  const closeModal = document.querySelector(".close");
  
  // Función para abrir el modal
  document.querySelectorAll('.view-more-btn').forEach(button => {
    button.addEventListener('click', (e) => {
      const cardId = e.target.getAttribute('data-card');
      console.log(cardId);
  
      // Configurar código según la tarjeta
      if (cardId && cardCodeDetails[cardId]) {
        modalCode.textContent = cardCodeDetails[cardId].code;
      }
  
      modal.style.display = "block";
    });
  });
  
  // Cerrar modal
  closeModal.addEventListener('click', () => {
    modal.style.display = "none";
  });
  